
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/juragi
    username: juragi
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver
    
mybatis:
  mapper-locations: mapper/*.xml

server:
  port: 8080