
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/board
    username: board
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    
mybatis:
  mapper-locations: mapper/*.xml

server:
  port: 8888